name: 'Build and deploy Jekyll (v4) for GitHub Pages'
description: 'A simple GitHub Action for producing and deploying Jekyll v4 build artifacts with GitHub Pages dependencies'
inputs:
  source:
    description: 'Directory where the source files reside.'
    required: false
    default: ./
  future:
    description: 'Publishes posts with a future date. When set to true, the build is made with the --future option which overrides the future option that may be set in a Jekyll configuration file.'
    required: false
    default: false
  build_revision:
    description: 'The SHA-1 of the git commit for which the build is running. Default to GITHUB_SHA.'
    required: false
    default: ${{ github.sha }}
  verbose:
    description: 'Verbose output'
    required: false
    default: true
  token:
    description: 'GitHub token'
    required: true
    default: ${{ github.token }}
outputs:
  page_url:
    description: 'URL to deployed GitHub Pages'
    value: ${{ steps.deployment.outputs.page_url }}

runs:
  using: 'composite'
  steps:
    - name: Setup Pages
      uses: actions/configure-pages@v3
      with:
        token: ${{ inputs.token }}
    - name: Build with Jekyll
      uses: dunkmann00/jekyll-v4-build-pages@v2
      with:
        source: ${{ inputs.source }}
        future: ${{ inputs.future }}
        build_revision: ${{ inputs.build_revision }}
        verbose: ${{ inputs.verbose }}
        token: ${{ inputs.token }}
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v1
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v2
      with:
        token: ${{ inputs.token }}
